baseurl = "http://linux-kurssi.dy.fi"
publishDir = "pipublic"
languageCode = "fi-fi"
title = "Linux-kurssi"
theme = "schoolbook"

pluralizeListTitles = false
#SectionPagesMenu = "main"
canonifyurls = true
[blackfriday]
    sourceRelativeLinksEval = true
    smartypants = false

[Params]
    description = "Linux-kurssi lukiolaisille"
    author = "Petri Salmela"
    email = "linux@petrit.net"
    github = "https://github.com/pesasa/"
    cssstyle = "bluebook"
    logo = "/images/Awesome-Tux.svg"
